In [1]:
from pyspark.sql import SparkSession

In [2]:
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages "org.apache.hadoop:hadoop-aws:3.3.4" pyspark-shell'

In [ ]:
spark = SparkSession.builder \
    .appName("S3JSONAnalysis") \
    .config("spark.jars.packages", "org.apache.hadoop:hadoop-aws:3.3.4") \
    .getOrCreate()

In [11]:
days = ['2023-05-15', '2023-05-16', '2023-05-17', '2023-05-18', '2023-05-19', '2023-05-20', '2023-05-21', '2023-05-22', '2023-05-23', '2023-05-24', '2023-05-25', '2023-05-26', '2023-05-27', '2023-05-28', '2023-05-29', '2023-05-30', '2023-05-31', '2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08', '2023-06-09', '2023-06-10', '2023-06-11', '2023-06-12', '2023-06-13', '2023-06-14', '2023-06-15', '2023-06-16', '2023-06-17', '2023-06-18', '2023-06-19', '2023-06-20', '2023-06-21', '2023-06-22', '2023-06-23', '2023-06-24', '2023-06-25', '2023-06-26', '2023-06-27', '2023-06-28', '2023-06-29', '2023-06-30', '2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04', '2023-07-05', '2023-07-06', '2023-07-07', '2023-07-08']

In [ ]:
for day in days: 
    loaded_df = spark.read.json(f"ranking/webtoon_ranking_{day}.json")
    all_ranking_df = all_ranking_df.union(loaded_df)

In [16]:
all_ranking_df.count()

all_ranking_df\
    .coalesce(1)\
    .write\
    .mode("overwrite")\
    .option("header",True) \
    .json(f"ranking/webtoon_ranking_all_day.json")

In [19]:
whole_ranking_df = all_ranking_df\
    .select("group", "titleId")\
    .filter(all_ranking_df.group == "전체")

woman_ranking_df = all_ranking_df\
    .select("group", "titleId")\
    .filter(all_ranking_df.group == "여성")

man_ranking_df = all_ranking_df\
    .select("group", "titleId")\
    .filter(all_ranking_df.group == "남성")

In [23]:
whole_ranking_titleId = whole_ranking_df\
    .select("titleId")\
    .rdd\
    .flatMap(lambda x: x)\
    .map(lambda x: (x, 1))\
    .groupByKey()\
    .mapValues(sum)\
    .sortBy(lambda x: -x[1])

whole_ranking_titleId.collect()

[('769209', 374),
 ('641253', 312),
 ('747269', 149),
 ('747271', 143),
 ('808198', 140),
 ('717481', 134),
 ('775141', 131),
 ('780404', 129),
 ('773797', 129),
 ('792651', 120),
 ('727188', 120),
 ('777767', 120),
 ('776601', 120),
 ('783888', 114),
 ('783053', 112),
 ('784248', 112),
 ('804862', 112),
 ('730656', 110),
 ('758150', 101),
 ('736277', 101),
 ('802293', 96),
 ('783052', 89),
 ('183559', 78),
 ('650305', 76),
 ('774044', 75),
 ('648419', 69),
 ('710751', 67),
 ('812354', 67),
 ('773459', 59),
 ('602910', 55),
 ('807178', 53),
 ('597447', 48),
 ('743139', 38),
 ('802833', 35),
 ('774866', 31),
 ('703844', 31),
 ('797410', 29),
 ('793275', 28),
 ('735661', 28),
 ('795297', 24),
 ('807859', 22),
 ('721433', 22),
 ('773916', 19),
 ('733074', 17),
 ('796152', 16),
 ('796062', 16),
 ('795262', 13),
 ('772764', 12),
 ('654774', 10),
 ('797731', 10),
 ('800770', 9),
 ('807393', 8),
 ('811721', 8),
 ('798917', 6),
 ('725586', 5),
 ('798664', 5),
 ('790245', 4),
 ('796867', 4),
 ('797937', 3),
 ('750184', 3),
 ('798331', 3),
 ('679568', 2),
 ('783523', 2),
 ('721948', 2),
 ('748831', 1),
 ('783524', 1),
 ('801475', 1),
 ('801505', 1),
 ('790239', 1)]

In [24]:
woman_ranking_titleId = woman_ranking_df\
    .select("titleId")\
    .rdd\
    .flatMap(lambda x: x)\
    .map(lambda x: (x, 1))\
    .groupByKey()\
    .mapValues(sum)\
    .sortBy(lambda x: -x[1])

woman_ranking_titleId.collect()

[('769209', 366),
 ('783523', 145),
 ('788167', 143),
 ('780404', 136),
 ('735661', 136),
 ('807859', 133),
 ('797410', 132),
 ('798917', 124),
 ('802293', 123),
 ('712362', 121),
 ('768469', 117),
 ('801711', 112),
 ('796152', 112),
 ('738487', 112),
 ('801475', 112),
 ('748831', 108),
 ('793275', 108),
 ('801505', 106),
 ('798664', 101),
 ('812354', 96),
 ('783524', 89),
 ('774866', 89),
 ('747269', 88),
 ('654774', 87),
 ('789652', 77),
 ('796867', 73),
 ('733280', 71),
 ('769568', 69),
 ('797731', 65),
 ('804653', 65),
 ('790239', 63),
 ('732988', 62),
 ('761461', 61),
 ('743838', 45),
 ('764129', 43),
 ('703844', 36),
 ('797184', 36),
 ('772725', 35),
 ('721433', 34),
 ('802079', 33),
 ('794155', 33),
 ('761722', 30),
 ('641253', 26),
 ('809706', 20),
 ('648419', 19),
 ('805737', 17),
 ('808455', 15),
 ('733074', 15),
 ('790404', 13),
 ('808994', 12),
 ('785251', 12),
 ('803891', 11),
 ('790245', 11),
 ('783539', 11),
 ('803934', 10),
 ('809590', 9),
 ('803649', 7),
 ('730174', 6),
 ('797937', 6),
 ('807019', 6),
 ('809694', 6),
 ('812412', 5),
 ('784248', 4),
 ('804329', 4),
 ('804832', 3),
 ('774040', 2),
 ('758667', 2),
 ('805907', 1),
 ('774831', 1),
 ('800778', 1),
 ('778967', 1),
 ('811219', 1),
 ('770523', 1)]

In [25]:
man_ranking_titleId = man_ranking_df\
    .select("titleId")\
    .rdd\
    .flatMap(lambda x: x)\
    .map(lambda x: (x, 1))\
    .groupByKey()\
    .mapValues(sum)\
    .sortBy(lambda x: -x[1])

man_ranking_titleId.collect()

[('769209', 370),
 ('641253', 327),
 ('747269', 148),
 ('747271', 145),
 ('783888', 143),
 ('808198', 141),
 ('804862', 136),
 ('775141', 135),
 ('773797', 129),
 ('777767', 124),
 ('776601', 122),
 ('792651', 120),
 ('727188', 119),
 ('717481', 115),
 ('783053', 112),
 ('730656', 112),
 ('784248', 110),
 ('650305', 103),
 ('736277', 102),
 ('758150', 101),
 ('710751', 91),
 ('783052', 89),
 ('774044', 89),
 ('802833', 85),
 ('183559', 85),
 ('807178', 83),
 ('602910', 70),
 ('597447', 69),
 ('780404', 67),
 ('648419', 66),
 ('743139', 65),
 ('773459', 63),
 ('795297', 62),
 ('800770', 43),
 ('795262', 41),
 ('772764', 36),
 ('773916', 29),
 ('807393', 26),
 ('802293', 20),
 ('746857', 19),
 ('796062', 14),
 ('780170', 11),
 ('789979', 8),
 ('750184', 7),
 ('721948', 6),
 ('779632', 5),
 ('733074', 4),
 ('703844', 4),
 ('803909', 3),
 ('798331', 3),
 ('679568', 2),
 ('670143', 2),
 ('812354', 2),
 ('759940', 1),
 ('811721', 1)]